---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://rootsongjc.github.io"
title: "Jimmy's Blog"
canonifyurls: true
theme: "Lanyon"
...
